sudo: required
language: ruby
services:
  - docker
rvm:
  - 2.4.1
env:
  - COMPOSE_FILE=./docker-compose.yml

before_install:
  - docker-compose build --pull
  - docker-compose up -d

before_script:
  - docker-compose exec -T web RACK_ENV=test bundle exec rake db:create
script:
  - docker-compose exec -T web RACK_ENV=test bundle exec rake db:migrate
  - docker-compose exec -T web bundle exec rake rubocop
  - docker-compose exec -T web bundle exec rake
